project_id = "nflwheveqglnxgfmimpq"

[auth]
enabled = true

[functions.diagnose-appliance]
verify_jwt = true

[functions.send-maintenance-reminder]
verify_jwt = false

[functions.send-critical-alert]
verify_jwt = false

[functions.paystack-initialize-transaction]
verify_jwt = true

[functions.paystack-verify-transaction]
verify_jwt = true

[functions.paystack-cancel-subscription]
verify_jwt = true

[functions.predict-maintenance]
verify_jwt = true

[functions.send-booking-notification]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false